// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: proto/service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BTCServiceClient is the client API for BTCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BTCServiceClient interface {
	// CreateTransaction creates a new record for BTC transaction.
	// Only single transaction will created by this RPC for a specific User.
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	// ListTransaction get the list of records for BTC transaction.
	// The record can be filter by specific User.
	ListTransaction(ctx context.Context, in *ListTransactionRequest, opts ...grpc.CallOption) (*ListTransactionResponse, error)
	// GetUserBalance get the latest balance for a specific User.
	GetUserBalance(ctx context.Context, in *GetUserBalanceRequest, opts ...grpc.CallOption) (*UserBalance, error)
}

type bTCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBTCServiceClient(cc grpc.ClientConnInterface) BTCServiceClient {
	return &bTCServiceClient{cc}
}

func (c *bTCServiceClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/BTCService/CreateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bTCServiceClient) ListTransaction(ctx context.Context, in *ListTransactionRequest, opts ...grpc.CallOption) (*ListTransactionResponse, error) {
	out := new(ListTransactionResponse)
	err := c.cc.Invoke(ctx, "/BTCService/ListTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bTCServiceClient) GetUserBalance(ctx context.Context, in *GetUserBalanceRequest, opts ...grpc.CallOption) (*UserBalance, error) {
	out := new(UserBalance)
	err := c.cc.Invoke(ctx, "/BTCService/GetUserBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BTCServiceServer is the server API for BTCService service.
// All implementations must embed UnimplementedBTCServiceServer
// for forward compatibility
type BTCServiceServer interface {
	// CreateTransaction creates a new record for BTC transaction.
	// Only single transaction will created by this RPC for a specific User.
	CreateTransaction(context.Context, *CreateTransactionRequest) (*Transaction, error)
	// ListTransaction get the list of records for BTC transaction.
	// The record can be filter by specific User.
	ListTransaction(context.Context, *ListTransactionRequest) (*ListTransactionResponse, error)
	// GetUserBalance get the latest balance for a specific User.
	GetUserBalance(context.Context, *GetUserBalanceRequest) (*UserBalance, error)
	mustEmbedUnimplementedBTCServiceServer()
}

// UnimplementedBTCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBTCServiceServer struct {
}

func (UnimplementedBTCServiceServer) CreateTransaction(context.Context, *CreateTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedBTCServiceServer) ListTransaction(context.Context, *ListTransactionRequest) (*ListTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransaction not implemented")
}
func (UnimplementedBTCServiceServer) GetUserBalance(context.Context, *GetUserBalanceRequest) (*UserBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBalance not implemented")
}
func (UnimplementedBTCServiceServer) mustEmbedUnimplementedBTCServiceServer() {}

// UnsafeBTCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BTCServiceServer will
// result in compilation errors.
type UnsafeBTCServiceServer interface {
	mustEmbedUnimplementedBTCServiceServer()
}

func RegisterBTCServiceServer(s grpc.ServiceRegistrar, srv BTCServiceServer) {
	s.RegisterService(&BTCService_ServiceDesc, srv)
}

func _BTCService_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BTCServiceServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BTCService/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BTCServiceServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BTCService_ListTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BTCServiceServer).ListTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BTCService/ListTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BTCServiceServer).ListTransaction(ctx, req.(*ListTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BTCService_GetUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BTCServiceServer).GetUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BTCService/GetUserBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BTCServiceServer).GetUserBalance(ctx, req.(*GetUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BTCService_ServiceDesc is the grpc.ServiceDesc for BTCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BTCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BTCService",
	HandlerType: (*BTCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransaction",
			Handler:    _BTCService_CreateTransaction_Handler,
		},
		{
			MethodName: "ListTransaction",
			Handler:    _BTCService_ListTransaction_Handler,
		},
		{
			MethodName: "GetUserBalance",
			Handler:    _BTCService_GetUserBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
