version: '3.7'
services:
  # btc
  btc:
    image: golang:1.19
    expose:
      - 8080
    tty: true
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      WORK: /go/src/github.com/moemoe89/btc
      GOPROXY: "http://module_proxy:8002"
    volumes:
      - ..:/go/src/github.com/moemoe89/btc:cached
  # timescaledb
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./timescaledb:/var/lib/postgresql/data
  # pgadmin
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
  # migration
  migration:
    image: migrate/migrate:v4.15.2
    volumes:
      - ../migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://test:test@timescaledb:5432/test?sslmode=disable", "up"]
    depends_on:
      - timescaledb
  # jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    ports:
      - "14268:14268"   # jaeger-collector HTTP server (tracer provider)
      - "16686:16686"   # HTTP server (browser UI)
  # rabbitmq
  rabbitmq:
    image: rabbitmq:3.11.8
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
