name: CI Workflow

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    uses: './.github/workflows/lint.yml'
  test:
    uses: './.github/workflows/test.yml'
  generate-proto:
    needs:
      - lint
      - test
    uses: './.github/workflows/generate-proto.yml'
