name: CI Workflow

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    uses: './.github/workflows/lint.yml'
  generate-proto:
    needs:
      - lint
    uses: './.github/workflows/generate-proto.yml'
