name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.x'
      - name : Install Protolint
        run: |
          go install github.com/yoheimuta/protolint/cmd/protolint
          export PATH=${PATH}:`go env GOPATH`/bin
      - name: Run Protolint
        run: |
          protolint api/proto
